apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "portainer.fullname" . }}
  namespace: opencloudcx
  labels:
    {{- include "portainer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  namespace: opencloudcx
  name: {{ include "portainer.serviceAccountName" . }}