apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "portainer.serviceAccountName" . }}
  namespace: opencloudcx
  labels:
    {{- include "portainer.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
